# Generated by Django 4.0.4 on 2022-04-24 02:29

import core.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=20)),
                ('picture', models.ImageField(blank=True, upload_to=core.models.upload_to_picture)),
                ('sub_channel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_channels', to='core.channel')),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('file', 'File'), ('video', 'Video'), ('text', 'Text')], default='text', max_length=10)),
                ('url', models.FileField(upload_to=core.models.upload_to_folder)),
                ('content_description', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('rating_count', models.PositiveIntegerField(default=0, editable=False)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='core.channel')),
            ],
        ),
    ]
