name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        db: [postgres]
        python-version: [3.9]
        include:
          - db: postgres
            db_port: 5432
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Prepare DB
      run: |
        python manage.py makemigrations --settings=media_platform.test.test_settings
        python manage.py migrate --settings=media_platform.test.test_settings
    - name: Run Tests
      run: |
        python manage.py test --settings=media_platform.test.test_settings
